const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
const PAGINATION_EMPLOYEES = "PAGINATION_EMPLOYEES";
const FETCH_EMPLOYEE_BY_ID_USER = "employeeById/FETCH_EMPLOYEE"
const FETCH_COMPANIES = "FETCH_COMPANIES";
const FETCH_COMPANIES_BY_ID_COMPANY = "FETCH_COMPANIES_BY_ID_COMPANY";
const FETCH_PROJECTS_COMPANY = "FETCH_PROJECTS";
const ADD_EMPLOYEE = "ADD_EMPLOYEE"; // New action type for adding an employee

export {
    FETCH_EMPLOYEES, FETCH_COMPANIES, FETCH_COMPANIES_BY_ID_COMPANY, FETCH_PROJECTS_COMPANY, FETCH_EMPLOYEE_BY_ID_USER, PAGINATION_EMPLOYEES, ADD_EMPLOYEE
}