const FETCH_EMPLOYEES = "project/FETCH_EMPLOYEES";
const FETCH_EMPLOYEE_BY_ID_USER = "employeeById/FETCH_EMPLOYEE"
const FETCH_PROJECT_COMPANY = "project/FETCH_PROJECT";
const FETCH_PROJECTS_USER = "project/FETCH_PROJECTS_USER";
const FETCH_PROJECTS_COMPANY = "project/FETCH_PROJECTS";

export {
    FETCH_EMPLOYEES, FETCH_PROJECT_COMPANY, FETCH_PROJECTS_USER, FETCH_PROJECTS_COMPANY, FETCH_EMPLOYEE_BY_ID_USER
}